apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-web-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/naveenshetty/go-web-app-aboutme.git
    targetRevision: main
    path: charts/go-web-app
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true  # Automatically redeploy if something changes
    retry:
      limit: 3  # Retry 3 times before rollback
  syncOptions:
    - ApplyOutOfSyncOnly=true  # Sync only when a difference is detected
